version: '3.8'

services:
  dashboard:
    image: ${DOCKER_REGISTRY-}blazorserver
    build:
      context: .
      dockerfile: src/Server.UI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UseInMemoryDatabase=false
      - DatabaseSettings__DBProvider=mssql
      - DatabaseSettings__ConnectionString=Server=sqldb;Database=BlazorDashboardDb;User=sa;Password=Password@123;MultipleActiveResultSets=true
      - AppConfigurationSettings__ApplicationUrl=https://architecture.blazorserver.com
      - SmtpClientOptions__Server=
      - SmtpClientOptions__Port=
      - SmtpClientOptions__User=
      - SmtpClientOptions__Password=
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=Password@123
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/CleanArchitecture.Blazor.Server.UI.pfx
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - sqldb
    restart: on-failure

  sqldb:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - "SA_PASSWORD=Password@123"
      - "ACCEPT_EULA=Y"
      - MSSQL_DATA_DIR=/var/opt/mssql/data
      - MSSQL_LOG_DIR=/var/opt/mssql/log
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backup
    ports:
      - "1433:1433"
    volumes:
      - ${USERPROFILE}\mssql_data:/var/opt/mssql/data
      - ${USERPROFILE}\mssql_log:/var/opt/mssql/log
      - ${USERPROFILE}\mssql_backup:/var/opt/mssql/backup
volumes:
  mssql_data:
  mssql_log:
  mssql_backup:
